title: Fisayo Ajayi
description: > # this means to ignore newlines until "baseurl:"
  Security engineer with an appetite for learning how to break and secure things.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Fisayo Ajayi # add your name
author-img: aj.jpg # add your photo
about-author: Security engineer with an appetite for learning how to break and secure things. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-github: # add your Github handle
social-linkedin: fisayoajayi # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: fisayoajayi.disqus.com

# Tracker
analytics: UA-165820667-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
